name: ai_123

publish_to: 'none' 

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  
  # HTTP requests - MySQL API
  http: ^1.1.0
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # Persian utilities
  persian_number_utility: ^1.1.3
  shamsi_date: ^1.1.1
  
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # JSON code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: fonts/Vazirmatn-Regular.ttf
        # اگر فونت‌های دیگر مثل Bold یا Medium دارید، اینجا اضافه کنید
  uses-material-design: true
  
  # Assets
  assets:
    - assets/update_history_records.json
